[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/shoomba/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *.internal
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[file_manager]
enable_object_processing: True

[webcam printer]
location: printer
icon: mdiPrinter3d
enabled: True
service: mjpegstreamer
target_fps: 30
target_fps_idle: 10
stream_url: /webcam/?action=stream
snapshot_url: /webcam/?action=snapshot
flip_horizontal: False
flip_vertical: False
rotation: 0
aspect_ratio: 4:3

[history]

[timelapse]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail-config]
type: git_repo
primary_branch: master
path: /home/shoomba/mainsail-config
origin: https://github.com/mainsail-crew/mainsail-config.git
managed_services: klipper

[update_manager timelapse]
type: git_repo
primary_branch: main
path: /home/shoomba/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: /home/shoomba/mainsail

[update_manager klipper_tmc_autotune]
type: git_repo
channel: dev
path: /home/shoomba/klipper_tmc_autotune
origin: https://github.com/andrewmcgr/klipper_tmc_autotune.git
managed_services: klipper
primary_branch: main
install_script: install.sh

# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: /home/shoomba/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh
[update_manager klipper-backup]
type: git_repo
path: /home/shoomba/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main
[update_manager mobileraker]
install_script: /home/shoomba/mobileraker_companion/scripts/install.sh
requirements: /home/shoomba/mobileraker_companion/scripts/mobileraker-requirements.txt
env: /home/shoomba/mobileraker-env/bin/python
managed_services: mobileraker
primary_branch: main
origin: https://github.com/Clon1998/mobileraker_companion.git
path: /home/shoomba/mobileraker_companion
type: git_repo
[update_manager Klipper-Adaptive-Meshing-Purging]
type: git_repo
channel: dev
path: /home/shoomba/Klipper-Adaptive-Meshing-Purging
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services: klipper
primary_branch: main

[update_manager led_effect]
type: git_repo
path: /home/shoomba/klipper-led_effect
origin: https://github.com/julianschill/klipper-led_effect.git
is_system_service: False


 
[update_manager motors-sync]
type: git_repo
path: /home/shoomba/motors-sync
origin: https://github.com/MRX8024/motors-sync.git
primary_branch: main
managed_services: klipper
virtualenv: /home/shoomba/klippy-env/
requirements: wiki/requirements.txt
system_dependencies: wiki/packages.json

## Klippain Shake&Tune automatic update management
[update_manager Klippain-ShakeTune]
type: git_repo
origin: https://github.com/Frix-x/klippain-shaketune.git
path: /home/shoomba/klippain_shaketune
virtualenv: /home/shoomba/klippy-env
requirements: requirements.txt
system_dependencies: system-dependencies.json
primary_branch: main
managed_services: klipper

#[update_manager klipper_tmc_autotune]
#type: git_repo
#channel: dev
#path: /home/shoomba/klipper_tmc_autotune
#origin: https://github.com/andrewmcgr/klipper_tmc_autotune.git
#managed_services: klipper
#primary_branch: main
#install_script: install.sh

[include octoeverywhere-system.cfg]
